title: Daniel Williams # your name (or website title) here
logo: "/images/UCD.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to an overview of my data analytics / data science projects to date.  
  <br><br>
  Qualifications to date: <br><br>
  University of Warwick - BSc Physics - 1st Class<br>
  University College Dublin - Prof Dip Data Analytics<br>
  Google Data Analytics Certificate<br>
  Data Camp - R Data Analyst<br>
  Data Camp - SQL Fundamentals<br>
  Data Camp - Python Fundamentals<br>
  Data Camp - Tableau Fundamentals<br>
  IASSC - Lean Six Sigma Green Belt<br>
  Prince2 Project Management - Practitioner<br>
  Prince2 Project Management - Foundation<br>
  Scotwork - Advanced Negotiation<br>
  <br><br>
  <a href="https://www.linkedin.com/in/danieljwilliams5/"> View My LinkedIn Profile</a> 
  <br><br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
